server:
  port: 9000

spring:
  application:
    name: service-product
  datasource:
    url: jdbc:mysql://124.223.175.150:3307/sc?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1157
