server:
  port: 8082
feign:
  okhttp:
    enabled: true

my:
  host: 124.223.175.150
  db:
    port: 3308
    database: service-cart
    username: root
    password: 1157
  swagger:
    title: "购物车接口文档"
    package: com.example.cart.controller
