server:
  port: 8082
spring:
  cloud:
    sentinel:
      transport:
        dashboard: ${my.host}:8718
      http-method-specify: true # 开启请求方式前缀

my:
  host: 124.223.175.150
  db:
    port: 3308
    database: service-cart
    username: root
    password: 1157
  swagger:
    title: "购物车接口文档"
    package: com.example.cart.controller

feign:
  sentinel:
    enabled: true # feign整合Sentinel

