server:
  port: 8085
my:
  host: 124.223.175.150
  db:
    port: 3308
    database: service-item
    username: root
    password: 1157
  swagger:
    title: "商品管理接口文档"
    package: com.example.item.controller
